import { NextResponse } from "next/server"

import { saveHomePage, fetchHomePage } from "@/lib/home-page-api"

import type { HomePageApiData } from "@/types/api-home-page"

function removeTemporaryIds(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(removeTemporaryIds)
  }

  if (!value || typeof value !== "object") {
    return value
  }

  const result: Record<string, unknown> = {}

  for (const [key, entry] of Object.entries(value)) {
    /*
     * Temporary IDs are generated by the frontend for
     * newly-created array items.
     *
     * They must never be sent to MongoDB.
     */
    if (
      key === "_id" &&
      typeof entry === "string" &&
      entry.startsWith("tmp-")
    ) {
      continue
    }

    result[key] = removeTemporaryIds(entry)
  }

  return result
}

export async function POST(request: Request) {
  try {
    const rawBody = (await request.json()) as HomePageApiData

    const body = removeTemporaryIds(rawBody) as HomePageApiData

    await saveHomePage(body)

    return NextResponse.json({
      success: true,
    })
  } catch (err) {
    console.error("[POST /api/save-home-page]", err)

    return NextResponse.json(
      {
        success: false,
        message:
          err instanceof Error ? err.message : "Failed to save Home page",
      },
      {
        status: 500,
      }
    )
  }
}

export async function GET() {
  try {
    const data = await fetchHomePage()

    return NextResponse.json(data)
  } catch (err) {
    console.error("[GET /api/save-home-page]", err)

    return NextResponse.json(
      {
        success: false,
        message:
          err instanceof Error ? err.message : "Failed to fetch Home page",
      },
      {
        status: 500,
      }
    )
  }
}
